services:
  app:
    image: coding-task-lab-devcontainer:latest
    container_name: coding-task-lab-dev
    build:
      context: ./node
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "13600:13600"
    command: sleep infinity
